---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: chat-api-secrets
  namespace: chat-api
spec:
  encryptedData:
    OPENROUTER_API_KEY: AgBAv21rlDWLBlxeytznaXJdE/+jgmN9KG8uzXhvDpj4QMCXtiv1r/nM2nfuX0gtYZ4+AawMwRPozZWBIcbnV9pY8a4VsyxuiSCFwmfoEx3lx2MP7L8nZdWBc0B/928B/KJ/Bobgw+v+NvKiH0nG9UszfLV+4xaS55IiOkHOaVW6wk+E2i3rXFL/puNn8ONeCVeiPXZ/uK1TxFSctTmuFE1rhDQMMgPv8bJeXZCOR/Y1/TPNg9AnslZvTDgK5BmYKn8gmxNHX0jP08pN1OsWPNQ1kXY61M/vwUWr/Fx3ja8yrPjJH2mLF+Uox6DexV2k73jlFyhE2CoDieYZzbYnjkCwCDfMY5v992kz1ps7F77ABdeJl4UFihxwpHz9BU0MD7NzhNJc+ZZuM73uISZ4qIjJrvgkBzCo1e5+KlMdyfC/hd5mbPioO9ole51znovqlGfoaBH89udl/jMJB0lSK7zQtBVj7bYWJD0wJtc+VlJXsWcabO07dLjN6HjcMZHRXhm9YYpWChU+eOw1YjbJwYCvixCGAQsnZ/2OfbyY0vVVJKEyScblmOnaAWENrEOV1pZ3ndmOLZxfIRE7XNlFxUBw5ULclpP3vAo+WLaYe2G1ehOEEUQtrGzkfqnh7TpsGjdLy1K5S80bqRbPJtD9clTFNFlawypQy+kX3c0o6WNtkpJ0JoHAkZItyOogXpEi7EqzWCqtz1XemPC/6RCW+VjaZjuWwctmWeEPytue953quTekYs9z3SJAEuEgcVWTKmbjVVLLh13VmRyZYmOL190H6oJmzPsYi82R
  template:
    metadata:
      creationTimestamp: null
      name: chat-api-secrets
      namespace: chat-api
