apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chat-api
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/justgithubaccount/app-release
    targetRevision: main
    path: charts/chat
    helm:
      values: |
        image:
          tag: latest
  destination:
    name: CLUSTER
    # server: https://kubernetes.default.svc
    namespace: chat-api
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
