apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chat-api
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/justgithubaccount/app-release
    targetRevision: main
    path: charts/chat
    helm:
      valueFiles:
        - values.yaml  # Дефолтные values из чарта
      values: |
        image:
          tag: latest
        env:
          OTEL_SERVICE_NAME: "chat-api"
          OTEL_EXPORTER_OTLP_ENDPOINT: "http://vector-gateway.observability.svc.cluster.local:4318"
  destination:
    name: CLUSTER  # Будет заменено Kustomize
    namespace: chat-api
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true