apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chat-api
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"

    argocd-image-updater.argoproj.io/image-list: chat=ghcr.io/justgithubaccount/chat-api
    argocd-image-updater.argoproj.io/chat.update-strategy: semver:~1.0
    argocd-image-updater.argoproj.io/chat.helm.image-tag: image.tag

    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: infra/clusters/dev/chat-values.yaml
    argocd-image-updater.argoproj.io/write-back-target-branch: main
    argocd-image-updater.argoproj.io/git-commit-user-name: justgithubaccount
    argocd-image-updater.argoproj.io/git-commit-user-email: kulikovyevgeny@outlook.com
spec:
  project: default
  source:
    repoURL: https://github.com/justgithubaccount/app-release
    targetRevision: main
    path: charts/chat
    helm:
      valueFiles:
        - values.yaml
        - ../../infra/clusters/dev/chat-values.yaml
  destination:
    name: CLUSTER
    namespace: chat-api
  syncPolicy:
    automated:
      allowEmpty: true
      selfHeal: true
      prune: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PruneLast=true
