apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chat-api
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/justgithubaccount/app-release
    targetRevision: main
    path: charts/chat
    helm:
      valueFiles:
        - values.yaml  # Дефолтные values из чарта
        - ../../infra/clusters/dev/chat-values.yaml  # overlay для dev
  destination:
    name: CLUSTER  # Будет заменено Kustomize
    namespace: chat-api
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true