---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: chat-github
  namespace: argocd
spec:
  encryptedData:
    GITHUB_TOKEN: AgDaaztNFNBTqtw7l8SrtaPYpQokc0P3hrzmqhn4f8JtT67wEvr3NjAlPUqOkd0SYXM0utS0t+awIwXIra2HuL1UDD0130wZFiz1mZAaZOmVDQNUsZx4v79say+KIncLCVxnMzJcrlKozN0vB0ybmrWQcZJ9HeQsT0kdbbYANEMGXjm98e0Rze1ThIMfBhCguQpbyTyCCd9bsmT0Clt5SJFTR55XeULiKkSdg2qyZbf5lVfyHCKH81bi+BB+wrgfb73O2codtUBd6Ps4yHfQMVuWrY6ca0TBcFgHEH2AhAJpwU0RQP90cY41Zo/6DnB49KF5i24dnelNWzREP0V2BChB/HSjdIUNJCHd2yzWl+60r6jveS53DNtn75fCeZDG6EJDpwhtceXM6wVMnk32VfQAD/WPh74OkwjYcL8LYKwiS+tHcTSeAnG2I+tSbsPKH/sxbMY5OmFRRfhB8/Rt5HMs17LvDONSbRPKbLalcRsOo2aQzriVMFDGouCDxmj5qDaA/UHXJWqghPJaYZOudG9UVp8MXkDKUyJzEk+7zV/2/gYecTtuIBP7+z+bmnTR5YxhIdbysLv5Av+yBaxew3rVnkr5/I5cRfeA2CmqszYIXcj7ySQoc0kWgQi4lNeHhonpcjfEFHczezU/CgNbsrAYvTQx7NI6BtC9wl22c56Pg/rjRHFUJmKXc8LhWYuZR3SufExHYPNnixxfXunU4Xwvlo+03ggiF6kQpbjfYTrs5+B4iH+UGDd3
  template:
    metadata:
      name: chat-github
      namespace: argocd
