---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: chat-openrouter
  namespace: chat-api
spec:
  encryptedData:
    OPENROUTER_API_KEY: AgApDOexTWU8J7gVykjaBH28Urk8gFrpAzTteXrwcs6ELpuc7oqAvrxeADb80gYu3HC9QUPx69UuY2/zSKXC+Nu8zYnSJlQxQ/C+EeCrShG+LrCfRD1zyKv6ijRKp6jQUouR7DE1VGIWedFoDstZNqgqRAc9nwDn/qAh/z5xdzvqxCxzDT6B+dQMRF6Ae1ytPKU+0xC+J/lTzL2yBkNR0ixjrQyAR52svNxnsV7rDEROsR6wUmLdhsXeXfwnV4bT7xuDhDd4x49QX3YmlLub6384rNaO7rSVjn4cvcoCH9WZzEoCgyR2d1morNjrkVjxHMCbzNqr8tI4wHuZuA762cKJxAKnPtkvsOsysc5QQlYhsBlSAo73NYc/OYkA3ULU+NLHCeegtBCOS2+nQMhbvdsCIzo0s+Hlb48oMzupF6Dl3YfoyQeJERJJ9yZYxkSj7wl5NfhGSUqkd9pDtKHuFkOm9N9+k4bzJdj4GJUxNhSVkq9QvxRtpC+zqxCN6JEpQ8nY9ZEAmcO2tx3Efb/mgN2dZtwa1WGgTF2IJoAAC2Ouzr64ttXXbOdP3m3dF8fLXcEn+CzN50clsgDcxVZN0Upykd2MQFCo4fm90ehbmUIlbl93wGmsHdL6QgJ7+Kb8DjVf758MYzx28ZCaRDgq1MMG+LwPuU/LZ3TKw1Wb7BaGdObkubfuDUVbHyFm1oB+ctdd6/lzNpEzDVQbC7FjJGmvcLAFiL/DHr0eKg2ufyUAmM258IY/1cyHBY94Nl//YJ/MP9jRxeNgCghlDlboPSiu+mziemNXu3Pj
  template:
    metadata:
      name: chat-openrouter
      namespace: chat-api
