---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: chat-api-db
  namespace: chat-api
spec:
  encryptedData:
    DATABASE_URL: AgBfUtiEN80vvluxDBWJzyZezVRuV6Ae2MeF1Osk1zBhguS/nWRpIuagZ5+kIQX0KG0ZoACWJHeWwNWatGGC9KtoHCx5LMg6gGIbYB3WlClrjqJVWypbE8YboYoc05iejwowCcNcbPloz4Q5XUTuUFPGl1qesxrHwkGew+2mMg9dfJzx4tl/5iuA1ARnYL17w+2B3K50tGqZlqPxrQ4DxTaBeln+lvoJo727jIwztu+qGT27kpxANYKUV/91+auX00ZkuoFY+WwpVjlR9NzaPRZQuO78A5CUutnU0d5OR4vaX8v0B2+fZo54CKWXRILn8gToAv1RrU/68hO9CQ8dsM6aIgkD/1TgB0HlGv62P3nwEiEY+vTny57sauDD9hVZZaH28tvI8yZryDntq+p3dMfezV+ABHumtoHO4Yx+QJgwJXb58BD+z/oZ6xkKl/axVCcEOzx0yuUlwASjhxUSrXgik6dTdfJKVPjIQXx7EY2D4XzZXUS6OjEbB9jqDf99ppnh0rUugCYr0LMM90Linhf3dv2bc2wOoS5Y0r8qSKjQ85RLNEMwc3sBywCMTVQK/1jZcb4/9vROK1QuzEzGKpY/br468RIl3HHbMHhP/YDS4b8HA1Xx6Q5VM+uaed/cXRzipGPfsUfV+CTIL3fselGjnf/twoFVaP4cvMA5YC3QHv0nxMk8D0xZpubWAmJZRny9jV9hTK4629Mbl0s/pQFVap98HGv3e9ub/0P0C71NMMowRDAvyjYmyYSiFjI1QHCBLle4I5Po8SZUFqs4FIyFpLw773mv
  template:
    metadata:
      creationTimestamp: null
      name: chat-api-db
      namespace: chat-api
