---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: chat-postgree
  namespace: chat-api
spec:
  encryptedData:
    DATABASE_URL: AgCQSaAVwquDckUlU+i0uvXBhsn1suufGpABOX2uV6b2TUL3ddsJU62uUcoBXhG4oZaKNs06y0Wus34c9qQkwWwfLCjhMYYVAhcR1HkAP2CYBaruKLsTBesSNfnN9LzJVJlnB84Qg/g1Xse5jvFCQaTlt6wbNfjA+5YcP8wqTS/YJAdfY6XY8pHF4if9K7+x7/iFpQvpR91QzdjOtpMU4HCnq1nNEej/Ang71J/UPXK+TZetbHJkMh+mNoY+Fy5A8sE8HS+H/wGznxf0AocauyEHFOiY94N6gGEHhq6KNK+6Fvq69arGLWxo3krB58s+4SY4dC2p1YCDoPBSiBAJKh1IN5U/JPdIvDkwko99kPVM72A+6vJ4qKsMGpxc2yWa4RBG6qUxJ53yTLS6bBurfUhqtBmhrEfcCCpQQ602FL3gXvrOkJq8XfUBU5GNeZw85EHPdjRvAKEw11t4kMg+v7TLO0qp7cBUs2AoQ8LhAVSYQT7IkCC/Bf9GfepGsYQsqUNKMsiDSmg2N+mxzKkOPDBKJArioLW/DWxQms7WWZ6y1SwxBXt8wa9tyyhHT2/YGDHdxvekAjUy1MKLHZRdC+o0OLg9EZGxrjrQscZo6yU6aSAw/gt7glwRbg24T/cBf6tvhy5r4buY2l0tMdDe9H+DDIN37u6O4c7QeeQlvwexdwpCb8ojhUsTWwYafwMiWYsYm/Za3jhVsDg9D6wiLC6cPRzIazRhjGqfnpngwbQukCOdqf3nNDuPA9v8WYtC95Zoxf9g4qxQvGyC/ZSHf5y/I1k76A==
  template:
    metadata:
      creationTimestamp: null
      name: chat-postgree
      namespace: chat-api
