# Override values для dev окружения
replicaCount: 1

image:
  tag: "dev"

env:
  ENVIRONMENT: "development"
  LOG_LEVEL: "DEBUG"
  OTEL_SERVICE_NAME: "chat-api-dev"

resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
  limits:
    memory: "256Mi"
    cpu: "200m"

namespace: "chat-dev"