# override values для dev окружения
replicaCount: 1

image:
  tag: "dev"

env:
  ENVIRONMENT: "development"
  LOG_LEVEL: "DEBUG"
  OTEL_SERVICE_NAME: "chat-api-dev"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://vector-gateway.observability.svc.cluster.local:4318"
  OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_LOGS_EXPORTER: "otlp"

openrouter:
  apiUrl: "https://openrouter.ai/api/v1/chat/completions"
  defaultModel: "anthropic/claude-opus-4"

resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
  limits:
    memory: "256Mi"
    cpu: "200m"

# [?] Автомизировать вальюсы относитильно того что если он оверлейтся на уровне разрешений (clusters) для роли (roles)
# как-то добится чтобы он еще и создавался автоматам и не конфиликтовал, скорее всего есть очевидное решение
namespace: "chat-api"
