apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# All app names must be unique across the ArgoCD instance
# So let's prefix the app names with the cluster name (dev- | demo-worker1-)
# namePrefix: dev-
resources:
  - ../../base/addons/sealed-secrets
  - ../../base/addons/ingress-nginx
  - ../../base/addons/cert-manager
  - ../../base/addons/reflector
  - ../../base/addons/external-dns
  - ../../base/addons/longhorn
  - ../../base/addons/observability/loki
  - ../../base/addons/observability/grafana
  - ../../base/services/agent/chat
  - ../../base/addons/external-secrets
  - ../../base/addons/observability/vector-gateway
  - ../../base/addons/argocd-image-updater

patches:
  # Override .spec.destination.name
  - path: destination.yaml
    target:
      kind: Application