apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-

resources:
  - ../../../base/addons/ingress-nginx
  - ../../../base/addons/cert-manager
  - ../../../base/addons/external-dns

patches:
  - path: destination.yaml
    target:
      kind: Application