apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namePrefix: dev-
resources:
  - ../../base/addons/sealed-secrets
  - ../../base/addons/ingress-nginx
  - ../../base/addons/cert-manager
  - ../../base/addons/external-dns
  - ../../base/addons/longhorn
  - ../../base/addons/observability/loki
  - ../../base/addons/observability/grafana
  - ../../base/services/agent/chat
  - ../../base/services/llm/gateway

patches:
  - path: destination.yaml
    target:
      kind: Application