services:
  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: litellm
    restart: unless-stopped
    env_file:
      - .env.litellm
    ports:
      - "4000:4000"
    volumes:
      - ./litellm-config.yaml:/app/config.yaml
    command: --config /app/config.yaml # --detailed_debug
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    stop_signal: SIGINT
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  chat:
    build: ./apps/chat
    container_name: chat
    restart: unless-stopped
    env_file:
      - ./apps/chat/.env
    environment:
      - LLM_API_URL=http://litellm:4000
    ports:
      - "8000:8000"
    depends_on:
      - litellm
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    stop_signal: SIGINT
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3