apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul-mesh
  namespace: argocd
  labels:
    app.kubernetes.io/component: mesh
    app.kubernetes.io/part-of: consul
  annotations:
    argocd.argoproj.io/sync-wave: "12"
spec:
  project: default
  source:
    repoURL: https://github.com/justgithubaccount/app-release
    path: charts/consul
    targetRevision: HEAD
    helm:
      releaseName: consul-mesh
      values: |
        global:
          name: consul
          datacenter: dc1
          tls:
            enabled: true
            enableAutoEncrypt: true
            
        # Zone: Application Plane only
        ui:
          enabled: true
          service:
            type: ClusterIP
            
        connectInject:
          enabled: false  
          # default: false  # Opt-in for production
          tls:
            enabled: true
          transparentProxy:
            defaultEnabled: false
          metrics:
            defaultEnabled: true      # OpenTelemetry ready
            defaultPrometheusScrape: true
            
        ingressGateways:
          enabled: true
          defaults:
            replicas: 2
            service:
              type: ClusterIP
            tls:
              enabled: true
              secretName: wildcard-syncjob-tls
              
        # Prometheus integration
        prometheus:
          enabled: true
          
        # Everything else disabled
        server:
          enabled: false
        client:
          enabled: false
          
  destination:
    name: CLUSTER
    namespace: consul
  syncPolicy:
    automated:
      selfHeal: true
      prune: true