replicaCount: 1

image:
  repository: ghcr.io/justgithubaccount/chat-api
  pullPolicy: Always
  tag: "latest"

containerPort: 8000

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10

livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 30

serviceAccount:
  create: true
  annotations: {}
  name: ""

env:
  OTEL_SERVICE_NAME: "chat-api"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://vector-gateway.observability.svc.cluster.local:4318"
  OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_LOGS_EXPORTER: "otlp"
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"

secretsRefName: "chat-api-secrets"
dbSecretRefName: ""

secrets:
  openRouterApiKey: ""
  llmApiUrl: "https://openrouter.ai/api/v1"
  chatModel: "anthropic/claude-opus-4"
  projectName: "ChatMicroservice"

namespace: "chat-api"