---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCG/K3uD9ichzmS18vaFNNhWwnz/qU6NqZMSYbljXm1rDXIps2yOwPn3QKQ5DKYp8R0ksHn7lF9OonbWEpJ5M3ADDoDXqSI9Eg8cII+Xdn4Jx56D4K92dPWEYGkwClayCwAVFMBUgY4mzzQKiCDlA5a4eabQ8Nk6bjrrquYXAiWfPSb2S8e+agOstk6a5XDtS7A0FsXv2MBN/qRQk4fZxnKD5+9e0RmQ79YHX7NjRlqSPopCrEt//dP4h5VFMKo/xxicu8YB0xScDVg0DaJy3s+NKnaCMZ+QcNp17z4Dnn3F949/KZfZCJ/Kk33H+1wRcOsriBFbWcuUZXAZoTXEld0kF5ohVfH9uf8EISJEHbcmRupoU4DFRpx+B/D0XTjfcxzSx6mr4rJVcdZoKpwigA63FXgyF2uu0rWoTSW6WAt7SbVheOoklHd4froHgxRW6IGexVE68u+Dd/408CPgAXhdydORd8WLPFssEZeGczH1laogauAeyQp1CvTHW0PHXEsT3a+WZt/TLN95g/fN1gnjEFI8w9X7OSkNY6wZ5WT+Ggy/g9i4betpV/6IZSZNf9xD1uVXj7bhi1m1oy/ODaAI5T+2bV8CvVMbyG30lcTFCx0Ze4SwGG5qRt+MCmdHv4mIUYsCvS+1zvbqo/dZq081f1YwGqCsVGb1PxgYRSHLBGjXwZXVzw35r7i7e5J/8ek+m2iMLdW4cHeSyNg9mq2QyIplkRC4nxde+4I5i95ZRk+GvBt7OCR
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
