apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.9.0
      helm:
        values: |
          preUpgradeChecker:
            jobEnabled: false
  destination:
    name: CLUSTER
    namespace: longhorn-system