apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chat-api.fullname" . }}
  labels:
    {{- include "chat-api.labels" . | nindent 4 }}
    backstage.io/kubernetes-id: chat-api
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "chat-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chat-api.selectorLabels" . | nindent 8 }}
        backstage.io/kubernetes-id: chat-api
    spec:
      containers:
        - name: chat-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          env:
            {{- toYaml .Values.env | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
