apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-api-vector-config
  namespace: chat-api
data:
  vector.toml: |
apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-api-vector-config
  namespace: chat-api
data:
  vector.toml: |
    [sources.otel]
    type = "opentelemetry"
    address = "0.0.0.0:4318"

    [sinks.loki]
    type = "loki"
    inputs = ["otel"]
    endpoint = "http://loki.observability.svc.cluster.local:3100"
    encoding.codec = "json"
    labels.app = "chat-api"
    labels.env = "public"

