apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-api
  namespace: chat-api
  labels:
    app: chat-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-api
  template:
    metadata:
      labels:
        app: chat-api
    spec:
      # topologySpreadConstraints:
      #   - maxSkew: 1
      #     topologyKey: kubernetes.io/hostname
      #     whenUnsatisfiable: ScheduleAnyway
      #     labelSelector:
      #       matchLabels:
      #         app: chat-api
      volumes:
        - name: logs
          emptyDir: {}
        - name: vector-config
          configMap:
            name: chat-api-vector-config
      containers:
        - name: chat-api
          image: ghcr.io/justgithubaccount/chat-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://localhost:4318
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: http/protobuf
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_LOGS_EXPORTER
              value: otlp
            - name: OTEL_SERVICE_NAME
              value: chat-api
          envFrom:
            - secretRef:
                name: chat-api-secrets
            - secretRef:
                name: chat-api-db
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 10
          volumeMounts:
            - name: logs
              mountPath: /var/log/chat
          command: ["/bin/sh", "-c"]
          args:
            - uvicorn app.main:app --host 0.0.0.0 --port 8000

          # resources:
          #   requests:
          #     cpu: 512m
          #     memory: 512Mi
          #   limits:
          #     cpu: 1024m
          #     memory: 1024Mi

        - name: vector
          image: timberio/vector:0.47.X-debian
          command: ["/usr/bin/vector"]
          args: ["--config", "/etc/vector/vector.toml"]
          volumeMounts:
            - name: logs
              mountPath: /var/log/chat
            - name: vector-config
              mountPath: /etc/vector
          # resources:
          #   requests:
          #     cpu: 50m
          #     memory: 64Mi
          #   limits:
          #     cpu: 150m
          #     memory: 128Mi
