apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chat-api
  namespace: argocd
  labels:
    app.kubernetes.io/name: chat-api
    app.kubernetes.io/part-of: chat-platform  
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: chat-api
    app.kubernetes.io/managed-by: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/justgithubaccount/app-release.git'
    targetRevision: main
    path: manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: chat-api
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:           # (Best practice для секретов и автогенерируемых полей)
    - group: "apps"
      kind: "Deployment"
      jsonPointers:
        - /spec/template/spec/containers/0/image
