---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: litellm-secrets
  namespace: chat-api
spec:
  encryptedData:
    OPENROUTER_API_KEY: AgAA97voVNZhDb8Fb3eKA2OlOiYaAvpOoI1BHattojRGol9ZJczirO2NiNYILxsiLMVWg/hOLBSmd0zjG3Ex12q7a+Z5t4DGEuDKzPJ2uELXhpfaAUjZhVLNaTlfygCzsq3RZGsKpbWIVntJvcAQaFwQl2qS5XMxPIHw9eWqopr5agrmz7olfJ1FPAHj++TfkjeXgiF6e8JoEq7OyolhBJtkTJv7230SgChRLI2eSw6/l3X+fGMCQJDtXogVrdZjJGgUktV55GUdHYCOGiE+iqtq767h3u8Pjby1N6uTfZPXlGwJO0ojv3zNys6YN/ArjcU1IRSf4gntcim+fvjBlCJ3jCQtNeTxGwZhICi5vXYzKmaSTqZba10Njcr8JO2o06SHJdhzeRgs0mkE8GEBfn6PvFQIF5ChkU+JetN9MDYlheixXWOM7nbaFg3YHVcPBX9vDV3go+QD5oah9gD4E3/1an20lFQ766yNn8DX3/LBBCQybKmECL62hXVv2Zvn5dcOq/sIFkrO/O/vtUhY998XJNwKmsv3Ic+VHK2h9rrb85gRhAXSH3XbH2FvufhvFBTLAY69GRoIiFruP860QjxFsEDaTX/2mHPkI5k+g9q75C91pjPtRKYH2oQINcGxtvrNR7QMOZUoWNMuWftUEQncJc3QsOflRCq5TSHz969uBTTjeTEcpWRD1FBFDywDNqM17G5ZGAv0ER9hPp3fYwffdeuT43B21l83bl+H2AQe4EkCcs/um/bIAm+QFUXT/QntoFAIayk1Yh2wd3AATgwpjP3W4TC0m02m
  template:
    metadata:
      creationTimestamp: null
      name: litellm-secrets
      namespace: chat-api
    type: Opaque
