---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: litellm-secrets
  namespace: chat-api
spec:
  encryptedData:
    OPENROUTER_API_KEY: AgAP5DcD9CZ/6saHb/LP4tHSOwmo5imtyn4WAxH64fDyi82D677azP1APJa/ZdXs8UorBOBKTuw9lnWkHv2oE8j8eh1tuq/ocwSpOYdW2HeSMzYjJ+D7bf08o8xxjmFTIUxTwMYx6b3eCb7TVAFgrPM0hNAePfhEsO+WIAzzCJ4IZqh/gU1dhvYEw3Ojghd+EXNB254eSIXsMWHlRss4HBdRHH0JPbn9qfzTaa2vBfO2tv/yjPFhKLtDh9XLWdCpdoZTgizbsG5H1IWieTT+ycu4wVRe3j5jU0Fm9yKooObXDEzxBFpB7cUpUvl0zgTUqoHEqQLI0UGbpPPtPqAS4MvMAdf/eVDBwdJWMdPPvWSRMibUzptzxJ88MOrjHmqq6HeR835ptDL7cceF8k6ooL7YC1r4WFD6h1SLUmR8NbBzKzGhyxXxb5g2pASzIU9wvpjLyORq3nq9ROONGf0F83VkAOtmwdDw5imJVQTLCXWEysbTaxWtl05cebIlCG9FCh9XV5LG/ZdcAwAFnV5RJiZHq7Vs0qQNqFYj3IvlPVtxCeBFR0pUz0M1OQ73ZebThPgFLigmOedMUqQrEZAZS51OtKYrCgjTpmqijfNVRDB7ZAUho8rHgX4OU2s/8MHu1WGE6zoSbLma0wEMjIY/3G6dX9pPaKIi0XUV2GF6JrJn/Ncse6jFdofBU9lLnXad6GhhMxZohuVWMlTCCuelL6n9YtPx3s90LYJ7PfJmwFWVGyuxqdZ4I841HN8MOcGZMdyQXuMK9dRACM7iwXgJufG/AxwETtDLY0ri
  template:
    metadata:
      creationTimestamp: null
      name: litellm-secrets
      namespace: chat-api
    type: Opaque
