---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: litellm-secrets
  namespace: chat-api
spec:
  encryptedData:
    OPENROUTER_API_KEY: AgBUVj3FlJg3fB1bkL8JlftOcdy8agHuQahnK/ufrFjhjGzcHz7MTefAWZuoTJjs8RNkvvxbjvzmez6vmWZGv28KASJbK0ARVb3Y+cwpgPSuthrnsIUzFYft3v5Gzf/lgT+siOjFeC4n9ObKYkwSyDkS4YHLdTOuNimIibWS//wECEcfU9H6huxUE6tt06LxlPm+B1jGY0EsJZqsfOz1uXRS/QVZ2TQmCsNzQ1ZW0U8XOHmMBJ7a8ylExUB1yGeuVl+veCStsTgniGANGENh4UCDvOTsi0tm58Zd0qtKiZUS5R8FGw9QBTRVIXHD8YWZdaGSX1cp8RMH1ZXB/oVrDBtrFlkn+ojWEDQVlmB+j+2ZCN07K/b3kL61DmmOCs737qFOH2xZk9teaSqDdYt4VWnNnlpIRE21KiLA2OqjtUvJvMKPRrgNm3hUYOlVF6MJL3AufH9+eYGiuol9ENLhXJxZXZAm4OuxWNijG8MGgfaooNMD480BA3OPPTrMfggUiPl14ZwC1Wwlg4oPR/KSlkZlB3/PD6E5e90ZmCErFSewZKCN8t832V4MMdaUfEKS7HPcFABTPU801urf+LqOdqAR2qoYikQcBWkx4ffavH3aTozjRymzBL09jX6F+uhnwwmYS2YqGNncsJ+3NWm+rH4PsP1HWoC4SXuiAVOfzQkRVE58X9AC6QNQuqQeL5kriCFf0CJuRymiKKWeVJF/VKs1kNwTlroxla87QxIjSQCYnuPMM/8R+QUEBtgPP9ARp77wMYme1ooahKE8VBXcw4jBZIuxLt9Ox5SI
  template:
    metadata:
      creationTimestamp: null
      name: litellm-secrets
      namespace: chat-api
    type: Opaque
