apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-vector-config
  namespace: chat-api
data:
  vector.toml: |
    [sources.file_logs]
    type = "file"
    include = ["/var/log/litellm/*.log"]

    [transforms.parse]
    type = "remap"
    inputs = ["app_logs"]
    source = '''
    . = parse_json!(.message)
    '''

    [sinks.loki]
    type = "loki"
    inputs = ["merge"]
    endpoint = "http://loki.observability.svc.cluster.local:3100"
    encoding.codec = "json"
    labels.app = "litellm"
    labels.env = "public"

