apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.30.1
    helm:
      values: |
        grafana-agent-operator:
          enabled: false

        loki:
          auth_enabled: false
          mode: monolithic

          commonConfig:
            replication_factor: 1
            storage:
              backend: s3
              s3:
                endpoint: s3.twcstorage.ru
                region: ru-1
                access_key_id: ${S3_ACCESS_KEY}
                secret_access_key: ${S3_SECRET_KEY}
                insecure: true

          schemaConfig:
            configs:
              - from: "2024-04-01"
                store: tsdb
                object_store: s3
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h

          storage:
            bucketNames:
              chunks: ceae9495-3a627f83-8eba-441e-b648-37d41cded627
              ruler: ceae9495-3a627f83-8eba-441e-b648-37d41cded627
              admin: ceae9495-3a627f83-8eba-441e-b648-37d41cded627

          limits_config:
            allow_structured_metadata: true
            volume_enabled: true

          pattern_ingester:
            enabled: true

          ruler:
            enable_api: true

        gateway:
          enabled: false

        lokiCanary:
          enabled: false

        singleBinary:
          replicas: 1

        persistence:
          enabled: true
          size: 5Gi

        extraEnv:
          - name: S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: loki-s3-secret
                key: access_key
          - name: S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: loki-s3-secret
                key: secret_key

  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
