apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pvc
  namespace: observability
spec:
  volumeName: loki-pv  # важная явная привязка
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
