---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    api-token: AgA9ZK5bkdusQjGH1IRbr/TNj4V99nTtnKG+iDybRN5ho/tKaHKNUjweqlDWAJtbMFbt3nDq948IDtmajYjmqkhQLKRDG3kgd9FMyEcpJUp4cek0m2LYfGPgvlVBHn2fFVcPHjh9w9toowHW7f/ihYfPZRChQ4og93StXmgxVgj6huHK0AewwxBmeiprsybNdK91lwcZcHB2p7/5oQUjF+LoLil9tlrKzOZPgZMMaK9opAukAUORnYHzQZlFk42SkX+Aj/o79RHZ140mqSe5qDx1gOYUOPc1N8w0lMCNddrTdMiha7VxFaz9QUiqq0UcW4k+nco83PCLppIWivJ1A11yZUMPqwJoWcL5/wgenoecPqPIuyCQz0b1lCW4MgfyqLjHvRLQVAtA7Lrn44QvfdnQkzoXtqBtKtTq6ogON7N3p7XL2sptCl8pOHpC8+H5H8w40h5LuDs1yhbz+vko+kr/A7KhrlTmggQj9h89bP7DJPyeQoIoa7Hh88NW7bqKyl0SSos12ZzIh30h1BxdTF98v8ufIOtwOYtQ88/+d2WD4ihtFxqKZXwI393RiHpleGiXl4XK086isPeqhXYirPvoJ1j0z5Lt2MdL3I2A0AWmMhezzi3CsqwEEYOvrgWrNgcai2975qxuWZvAsR2/TvPG1ExQKlI1cq8Bmnl7yOGYWRC0y1iVsbkVgx96xG1KKESqL5a1KRC2RfSBZJRQDCa107Cs/JYua8VQZp+dh3IlhEV3PcnCcdg+
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: external-dns
