apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
spec:
  source:
    helm:
      valueFiles:
        - infra/platform/values/external-secrets/base.yaml
        - infra/platform/values/external-secrets/dev.yaml
