apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  destination:
    name: CLUSTER  # ← Placeholder
    namespace: external-dns
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    chart: external-dns
    targetRevision: 1.17.0
    helm:
      values: |
        provider: cloudflare
        sources:
          - ingress
        domainFilters:
          - syncjob.ru
        policy: upsert-only
        logLevel: debug
        env:
          - name: CF_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: external-dns-secret
                key: CLOUDFLARE_TOKEN
  syncPolicy:
    automated:
      allowEmpty: true
      selfHeal: true
      prune: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PruneLast=true