---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: external-dns-secret
  namespace: external-dns
spec:
  encryptedData:
    CLOUDFLARE_TOKEN: AgC0Fgidl3N2GuW/ZzytAv40fdOXlE4Qoo7t0D6DJjI5ljXsZSLUhOAT5kXOpSR4I9Hx4z0zWqiLIuEO7d0wnpjutkWLdjr2qJ0JNIzeQLzZe453XOcXVO15pArS3Mz/YVu+zcCxrjqAcjk265F8SgfaJHHqYzRysP6NzeQXIe2NQ1LtS9XsjjKnDeRtDCTT9/uL8azA9EwbLY3fqfiZAKdI7i+YSY0U2xSUdEwcxHTf6f/3rTQgOk7soELmZWtBEMtGtmrf2lJut3DK6Craz8HIwlO6pLJ6oUeX4rkXRdpRa0oLad8+b5K+hP2sK1XjOqE13YbJr6U+S4mpY6O4NHTeiw5IW1QRGqZDNQRT0lThSFU3cH3NBIcl5TfsmQdcmR+U3wra970t31wk6h16/MUbgI8Fzla7z4568HUyMd7wTer6lSqJp7ZVVAUHRRMCTQ4rdS2y+7OT4Oyn8AKNEc6X9HP1XfiIho5b8e9vDhNz7KrNaKh4xQmb+Q5wMfwsBUT3NPq2ILoyj/nkD8jsIKEiIctRKGYCoTaokHtxBrLlG9/YRYllKwWMcJ7r9/9HzYhhDizfo589A6WtpQ2HC5b36sb7dZbaWkvQE0oJhIClvUCx4baXq3rA9DiSkc7DqgME0ZpS02b2qyANlbuXDWSl9BClkNCJO+yWenYTlmNlaZhPOXqje1k1ZJ2K3zq4P/omiHzSIS1OA7+pmBqVcGLMZyI/i6cDuk7PefoYJE3dj8Ad+hXUggMM
  template:
    metadata:
      name: external-dns-secret
      namespace: external-dns
