---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    api-token: AgAUP/eBQ+PZoIOtr/jWvWb7xPiaeE7hH5cmRjrfGPx6nMd5oKZVHqwqGAS4GMeamqUnJ0njgoHZTnS/wJ9XDks7Q+pe26ZXAI0BNzTt3XNGS/8O+Lx4saBJRtIST68tB7hsLViwhf0Hlkgk2HUp2JVI/wIZmR6oZvapQ0Aad72iicpWO3DDw/+Jeaof1V/9VhcuMgMnQCr+hTDSGLB3IllfXCbMxI6SOW5eVJptuKmXQcwRUzMIwIssiKl83CYr0p8T8/d/OER2Q69cvCACsJJLslJw+25Rxc7jUlHbd4ackzuWrByxGfTdoTrQ641Fnph7JXzFZv1ZR0KI9Ek55LWOvDsiEsq76w4E+SVP7+onwQXx946HvFH2iO6gclVoh310PSYvvuJ0iDaVd/O6/Dgz43gj2F9uw3hk2+2nMlAtckgu/rxcMWKFGJTofFdjSMFnwQuYtsLrwITBKlc5JBUu//pW3sSCzIeInxEzEDFlbrcxyVMAf6b2sIx2a+4NmSendx41ncSK7xtSlM3ziODICZUSFbTOHfWesiSEKM8Y7ds3v1YWTVoj/X/lwnW3Fl1LgqWnOXDzvpWMxHPw0atfmVZeUpiqKsFQpg0GfjB9EuLk0Jc+gHh4nvoQSbC1Qmqp4/9aXOaZQ1ksavoa7H4/EXUIsoI0ITw9KmtDou6EaRp0UTlxKm4t63INMvC6HOJ2MX3i/VpoG7fDY/y0aHgohTFrAW+PvCJmz9kxjJn/eIu6dby0i9+W
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: external-dns
