---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    api-token: AgBMxzBprbZSc+3mI95CSJyzCYjfP6mz97AQHti2DGyQouly12fX/lJ0zh0MFrUS5kO5COC6dnv1anxxlRd85beGgbxlinIfLPBXTd8EANItnU35gg/1ZjLYJxFPDUgsoOY+PkHKhu5jBsSluRwvwqncEPVz6kt/Ee5+WbJwiVbYNADONIKM8mZFN8/iBBGEF143rBfKEsTZw0RdyFjZQM/K7TTqh4P8HOplAhObddne93YRI90Z/juAy8tnVOVONfRzelVyTdD6H3IxFEApsWhXwiCdtASc+tX7pazRA+PlFl47iGHM1iqk5AiJU+taXwHiyjm1oARUt2rnC7kUqaTHjJgKzYoJMwH9aWk5Ik4rjVxFjEyRoLeWejk4N9+DmBVFzhT1TFdt4YDkeN5rp4tosPSMbKT9fO3L98J5xrb3D2/8Pww95/+AeOIi2jPW0rDCKyJ+TfT1W3U4uBNbjqIoI8Qu4gBac/Zbt6EPq/HwWpdDD9Gv8gGIklMP1eDxBEj8AjCsx+SuDRKAeQb03UOmBhFlf0766y2DoZcfYDLAZR654jk7vkkbYzuLtpHZYqB2uQcgRYpTmTrmEOmxL9V8aSK1C7Zyx2G8GmcjoxfaXWiSehkxuq6PpPx4w0rvKef3wcSyEVSU2ntkJxm4xw5uJMUbjC/rQA/5ng5LHQeMpAKQCnXNtpxYKl5nkbZAXu13GvAxLUWetIjbHRayu7a2CO46JoxkykqPJqOq7pvt/B+kvTNuMN5V
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: external-dns
