---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: litellm-secrets
  namespace: chat-api
spec:
  encryptedData:
    OPENROUTER_API_KEY: AgBz3GD5J8dAqp5r7kRY3LnmlNIHC5BSY7WVC8wEPmlkL1lWfnPTHBmEhT6eLeUTCqmVWEGdf+bsZ6RaTlgSvHOcJie3V3FgujcAQF5cZabOdR6LsTMtZ29ZYOkzT4/19Xf5lJkpqkRIyIl/g+zmEKH9P3OMQW51w6Ia97yazRZEZOGGigfnxOq+cX4/CD8vYJV9IdOpHjNnQKbRgPfEI/JG96ypN1F/i6fu/bl11HJTU4HuybM7/uk3BrZv5XyAxWk/tVprCAWhyRy5bMzR2IvQQ+LZGvZFS5Sj90GCXKLjTmpmjEUhDJBrBUnDgUH/Le/riEWHeQuZV2PJvsej9d01GcpEE/DqbPa4V7hXCLd8I5OtOMVcU1yG1H6IuIUl3/NKxw1xJUmM1GAoeM3fZZAegM/0zcfCmLCoTyljMdyly1DKQuBx3VFFvfgZQlUBJcUUK7V70cJeMu24JuveGG7Fi0LITReayoP1LhEcfjBaPvcROs5EJykwQRI7uzjEBnbUSL2nZJo9dEMBUqQwkhdCJXYLy1bWVPYC2YPeVLQHo5rtDh5MrjtIyOnHkfD2p3lsZ7hwckoIRHNq/bjvP5FiI7Ms3ojs9QG74yyEnLttUangRI8xZFBkMaJiZptBNhbldcEKpXZl9LcX3pC4vOXkk+SK6efQ9ey9n9tpAVrKH5AwYlvfvEpUl/tF5VaVR6Ay/DVPHG4j3gkGeKHpxEVlaBjZZPsQJrMpP00JYrQ+1GmSGY0Ksg5E08sCvrTNqbjtEl1YEhxZ8TnebUP7r85Tq3XQ9gZb9KGn
  template:
    metadata:
      creationTimestamp: null
      name: litellm-secrets
      namespace: chat-api
    type: Opaque
