---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: litellm-secrets
  namespace: chat-api
spec:
  encryptedData:
    OPENROUTER_API_KEY: AgCwSOlufTM1QhlI1qWvfls7anqVCSW+37N3sVhofHMRByLxlid3xeVDQbCKX+ncWWP50XvdZewr/Z/yJR6jT34txBPlhO1pL7joAGv8/0hrVwE923z80nLmjzwZmUJ3qiV0SvplGZk8PSZv9ySVzQuSryMeOa6zq1QhufG6wN3nu+NsHarHpx1Ps19jzSsBOCoTq+9/tGKvT4QWwXrAuCVpn4420q1G1LYhrkbiXh0F+MuNsB/meh7sUcDL7Fx/2ve6Q2y22z3JNg4pIS3YnhPiJsu526ePlBOpI8PezLrS77MYCuS7XWClnoDL4AtHdNN2iPx/QAUTfMs5Y4Fun+OjhXRzMNYJs8yFDjmb1ZEY88Yf60+7uWv2/Ys94g4QwIBlXZBxG0WxAmTBJ3lpqxYB+jmujNL+0kT5pxHHbX57Eo25I18/02kfGSQfJAj8OwXWwvKYtT16y0rDr2jo6bhPA7XZ8CoRe0x6tQTXv/exUrNmTZjP9r12J43pGY6V/P2pGCsJMDijBcILrKaEF7pJo5nGWMrQuDzc2yTn2qs7FOI+iSB2sqEH6iTKpxn2TaTkEyZrm2Ea5ePXEV8pjOVOe1V4OaJQgbJxa/u506dGbL24xeLOzQjPLGxZTDHj9mX7bpgYpPDZIcXhV9hjr7LLdWxU0uwyVK1p6xHwT89cxs4wlX4ODfgDEzCTYfTNbO8xMzeSSmUUZOgXBfJDmq76b09HI04xW7CbDJbfU4iRyfSZrxfATRAX4lpkDn0empzmUJhJJmSo4nJqjS3/Al3CgAnwvnYTB8uy
  template:
    metadata:
      creationTimestamp: null
      name: litellm-secrets
      namespace: chat-api
    type: Opaque
