apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vector-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2" 
spec:
  project: default
  source:
    repoURL: https://helm.vector.dev
    chart: vector
    targetRevision: 0.44.0
    helm:
      values: |
        role: "Stateless-Aggregator"
        service:
          enabled: true
          ports:
            - name: otlp-http
              port: 4318
            - name: otlp-grpc
              port: 4317
        customConfig:
          data_dir: /vector-data
          sources:
            otel:
              type: opentelemetry
              address: 0.0.0.0:4318
          sinks:
            loki:
              type: loki
              inputs: ["otel"]
              endpoint: http://loki.observability.svc.cluster.local:3100
              encoding:
                codec: json
              labels:
                app: "{{ host }}"
                env: "dev"
  destination:
    name: CLUSTER
    namespace: observability
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
