apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vector-gateway
spec:
  source:
    helm:
      valueFiles:
        - infra/platform/values/vector/base.yaml
        - infra/platform/values/vector/prd.yaml
