---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cert-manager-secret
  namespace: cert-manager
spec:
  encryptedData:
    CLOUDFLARE_TOKEN: AgCQWY2b+JEVJ7uF6XRtwnYbPSHjiu4XHuI7t6vB4fy/ZopjnyYYgLLaYueU9a+qFmHzpZT0A1PgSzR9lYRioD7NT3j4ONyu4xTSurq1XtBk9kESSMBPXfVBgga/UjOJTDhmfJpsmDeVPy1ZFdQbr3ByDxqjydLJJlZ0exkJ9VAtflBBMqoIRhgLZe+Ui0NT4LAJxX+pnmfepI4C/TpVkvlts1RbafzXfmMP3ecmtAcaAj0UpMYD7qzBm0cxCyvG5eZbO8M+WfNX8Qss3VkHlY9rGeS4GuY8gKIf5qEcmehdqkNolMbsjAVr1Q8C+lhETFhOgvKr8U1ycHT5Vi1Sek0PJO+mL5RoAhn87YixH4eP8n4swXr1EiDRNQoETOv66WnORb7Ilg/tCxE9YQcty7BHkTfOCCuc0rknLAWFWNombJ9DlJEUfBrgUeRTGSvmK0yN4I0qAJqwkINmiTK9l1CVbOWXoXAFnk1om3ZzB5yr4TWSXu/eBeSZ0MsFkx7gkzwoxeDEyVhShERgd39d43E3elrOlEiICwXSIGWpzOtIXCLzlF5kOv/fUp0qRM6oguvqNpelMXNp7q5r4jYUpJ2poniIAp9VSjSNmcnqz+uuAy634TNrklU7YxkANIzaSP1uc7pamO1HjyDE1IufmGhk+9x05fN0za7WPWWYNjMfkR0fDOOPsIFvXMXE+hUD8WxuqZciwJnfkWEodXiaJraOivRrW47Whzb7ludWE1Gi44Tv+oKuyYKh
  template:
    metadata:
      name: cert-manager-secret
      namespace: cert-manager
