---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAdL6zKmEAFi/1jQ01PtfoiVttPzRl/XBfVu5+2DleCItrWxhMHJycpjVLNAYd/CMnDDBq4CWbm5i2FRfIvaIQ2ThKj0ZQ2omgoS5kFpSunKOrcsty8I6ku5Mq8MyQXwopEdmC5ZivAtGNbt3bqOmrmLsLitj0pLdFQ3Rhl1tCvRd1+cwZwX+mgFj/H1+pFoSYs5S4d/jlNv49SVfx51Zg21bQ+A2HCfgvTY1OM6D6XJDqxXC1vWkBY1YZ+P5iJvkHr2a13AwoHwDw2x8635gnAt/joHLS46TOuzN33kUhXRimeIGeUps0ln1u1++eszsePyh3ItwtXEO5abUE6LUsEpX23v5WxZgQSWKsKSE+LclKei1yWqUMbtLZwsVvaeZbDMoScLtZjHjeRN4fGHehlwWBzrbS/MDMgZ6ptJhWr/S9LzRRfInsldFf9f9FP+942Z/0V5RxWzsmWih0zmF7GTCOff1uUNZnO6nGToxPa3/166hBczIG8xxJAELxeEri3WuAcaj7F4ctgN8qL+9PrhNDwaqtWMDJq9GvqIS+zgjI061DvVTlWis9FPralr/6SPe5OQtgV/tIA2/oxDWLBEzgcXCAcGNJNhX8yusD66UmHzLln0wMEhzFSty7+iQRMOgqxnVnbVd4y6Vy7b2kyQEiDqRfSz8L/z+zvkGo1IUIkPyuNpiuuFH5tbZdS3siQh0684G2sr9EDT6vZAbUNqI2iHn1twmhzflOA5/oGCqFirulA4IRr
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
