---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAdKN7nsRnDQyg/E+QtB4K9RNWv6ZnhbRtfQAS7xRnHHHaAQsY1FMZ86fzf6V06nzHW9RY2vHh51nDPYSYFAqI2Y8hDo7ZCveN0qoJ6JwD+nhaGPjS2Qn5BqIUrbLSMYt9aQwXaymAqJZEZDNLARU6mT0Xd+mXyHQcGoeBwvjWgdaisVpgSt81132tPR3HXHq+1CaWgzjvbH8lNJGlipMeIdxAQiO5MvD7Jk/CU+mtbr/tr2miqwwAwsxnuwpH98x3+SeOtcIROdn8TmLM6ZU6039LvWgYn3mlzctc3wZfDnTkk+dcOek2muPo7qsxxUaQKGWzfkgTT8013vFHAPovtReL0/T8oBgYly/OcL178X4o9DlOSJKx6cI5sMTI34kzO9l9WAfm7sT5kR3XOxn7VP4ojHtiTJt4n1C0knY/XB7vCuDwZsy56QMbr4YZXdCaGlS2KHOtAqlxMOz+y6gKLa34pkxvuNxhJT5ezMzbnfhMZl2VKIzfZGjpareStMui2oy0foIH4/Mea/FV3/Ty2dBAG0aynIPi9DvcdhrH9e8SDtvyl5ABypBF+bFB2l8cX8Oxt+G/2HWuMAJbwAHzMzmlnXHew3e5cTCZSCrUxEY6CMDBwZRaaxTyM70k6iuxaJwKgrUQwYjZjOBAJW2VZtBB1RHlU7/uCUT+FvqLmw7Nn83onXW0NIRy2mLJ4hcoYbYoeHcFcEi4Xlpk8pjDNMckbrIOldkE0XiW+L5kMhx1HR1b7iVzB
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
