apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chat-api.fullname" . }}-secrets
  namespace: {{ .Values.namespace | default "chat-api" }}
type: Opaque
stringData:
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | quote }}
  LLM_API_URL: {{ .Values.secrets.llmApiUrl | quote }}
  CHAT_MODEL: {{ .Values.secrets.chatModel | quote }}
  PROJECT_NAME: {{ .Values.secrets.projectName | quote }}
