# charts/chat/templates/secret.yaml
{{- if .Values.createInternalSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chat-api.fullname" . }}-config
  namespace: {{ .Values.namespace | default "chat-api" }}
type: Opaque
stringData:
  # OpenRouter Configuration
  OPENROUTER_API_URL: {{ .Values.openrouter.apiUrl | quote }}
  OPENROUTER_MODEL: {{ .Values.openrouter.defaultModel | quote }}
  {{- if .Values.openrouter.httpReferer }}
{{- end }}