apiVersion: v1
kind: Service
metadata:
  name: {{ include "chat-api.fullname" . }}
  namespace: {{ .Values.namespace | default "chat-api" }}
  labels:
    app: {{ include "chat-api.name" . }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.containerPort | default 8000 }}
  selector:
    {{- include "chat-api.selectorLabels" . | nindent 4 }}