apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Platform components managed through GitOps
  sourceRepos:
    - https://github.com/justgithubaccount/app-release.git
    - https://redhat-developer.github.io/rhdh-chart
    - https://charts.external-secrets.io
    - https://helm.vector.dev
    - https://kubernetes.github.io/ingress-nginx
    - https://charts.jetstack.io
    - https://grafana.github.io/helm-charts
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: backstage
      server: https://kubernetes.default.svc
    - namespace: observability
      server: https://kubernetes.default.svc
    - namespace: ingress-nginx
      server: https://kubernetes.default.svc
    - namespace: cert-manager
      server: https://kubernetes.default.svc
    - namespace: external-secrets
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
