services:
  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: litellm
    restart: unless-stopped
    env_file:
      - .env.litellm
    ports:
      - "4000:4000"
    volumes:
      - ./litellm-config.yaml:/app/config.yaml:ro
    command: --config /app/config.yaml
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    stop_signal: SIGINT
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  chat:
    build: ./apps/chat
    container_name: chat
    restart: unless-stopped
    env_file:
      - ./apps/chat/.env
    environment:
      - LLM_API_URL=http://litellm:4000
    ports:
      - "8000:8000"
    depends_on:
      - litellm
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    stop_signal: SIGINT
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  loki:
    image: grafana/loki:3.5.1
    container_name: loki
    ports:
      - "3100:3100"
    environment:
      - LOKI_LOG_LEVEL=warn
    volumes:
      - ./loki-config.yaml:/etc/loki/config.yaml
    command: -config.file=/etc/loki/config.yaml -log.level=info
    restart: unless-stopped

  vector:
    image: timberio/vector:0.47.0-debian
    container_name: vector
    restart: unless-stopped
    command: ["--config", "/etc/vector/vector.toml"]
    volumes:
      - ./vector.toml:/etc/vector/vector.toml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:10.2.2
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SECURITY_DISABLE_INITIAL_ADMIN_CHANGE=true
      - GF_LOG_LEVEL=warn
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources

volumes:
  loki-data:
  grafana-storage:
