image:
  tag: dev
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: chat.dev.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: chat-dev-tls
      hosts:
        - chat.dev.example.com
env:
  - name: LOG_LEVEL
    value: debug
