apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
spec:
  source:
    helm:
      valueFiles:
        - infra/platform/values/observability/prometheus/base.yaml
        - infra/platform/values/observability/prometheus/prd.yaml
