apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
spec:
  source:
    helm:
      valueFiles:
        - infra/platform/values/observability/grafana/base.yaml
        - infra/platform/values/observability/grafana/dev.yaml
