apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
spec:
  source:
    helm:
      valueFiles:
        - infra/platform/values/observability/tempo/base.yaml
        - infra/platform/values/observability/tempo/dev.yaml
